// This file was generated by a tool; you should avoid making direct changes.
// Consider using 'partial classes' to extend these types
// Input: BuffStruct.proto

#pragma warning disable 1591, 0612, 3021
namespace com.server.game.protobuf.proto
{

    [global::ProtoBuf.ProtoContract()]
    public partial class BuffStruct : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        {
            return global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);
        }
        public BuffStruct()
        {
            OnConstructor();
        }

        partial void OnConstructor();

        [global::ProtoBuf.ProtoMember(1)]
        public int buffConfigId
        {
            get { return __pbn__buffConfigId.GetValueOrDefault(); }
            set { __pbn__buffConfigId = value; }
        }
        public bool ShouldSerializebuffConfigId()
        {
            return __pbn__buffConfigId != null;
        }
        public void ResetbuffConfigId()
        {
            __pbn__buffConfigId = null;
        }
        private int? __pbn__buffConfigId;

        [global::ProtoBuf.ProtoMember(2, Name = @"num")]
        public int Num
        {
            get { return __pbn__Num.GetValueOrDefault(); }
            set { __pbn__Num = value; }
        }
        public bool ShouldSerializeNum()
        {
            return __pbn__Num != null;
        }
        public void ResetNum()
        {
            __pbn__Num = null;
        }
        private int? __pbn__Num;

        [global::ProtoBuf.ProtoMember(3)]
        [global::System.ComponentModel.DefaultValue("")]
        public string buffValue
        {
            get { return __pbn__buffValue ?? ""; }
            set { __pbn__buffValue = value; }
        }
        public bool ShouldSerializebuffValue()
        {
            return __pbn__buffValue != null;
        }
        public void ResetbuffValue()
        {
            __pbn__buffValue = null;
        }
        private string __pbn__buffValue;

        [global::ProtoBuf.ProtoMember(4)]
        public long createTime
        {
            get { return __pbn__createTime.GetValueOrDefault(); }
            set { __pbn__createTime = value; }
        }
        public bool ShouldSerializecreateTime()
        {
            return __pbn__createTime != null;
        }
        public void ResetcreateTime()
        {
            __pbn__createTime = null;
        }
        private long? __pbn__createTime;

    }

}

#pragma warning restore 1591, 0612, 3021
