// This file was generated by a tool; you should avoid making direct changes.
// Consider using 'partial classes' to extend these types
// Input: LoginInfoResponseDto.proto

#pragma warning disable 1591, 0612, 3021
namespace com.server.game.protobuf.proto
{

    [global::ProtoBuf.ProtoContract()]
    public partial class LoginInfoResponseDto : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        {
            return global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);
        }
        public LoginInfoResponseDto()
        {
            OnConstructor();
        }

        partial void OnConstructor();

        [global::ProtoBuf.ProtoMember(1)]
        [global::System.ComponentModel.DefaultValue("")]
        public string loginKey
        {
            get { return __pbn__loginKey ?? ""; }
            set { __pbn__loginKey = value; }
        }
        public bool ShouldSerializeloginKey()
        {
            return __pbn__loginKey != null;
        }
        public void ResetloginKey()
        {
            __pbn__loginKey = null;
        }
        private string __pbn__loginKey;

        [global::ProtoBuf.ProtoMember(2, Name = @"time")]
        public long Time
        {
            get { return __pbn__Time.GetValueOrDefault(); }
            set { __pbn__Time = value; }
        }
        public bool ShouldSerializeTime()
        {
            return __pbn__Time != null;
        }
        public void ResetTime()
        {
            __pbn__Time = null;
        }
        private long? __pbn__Time;

        [global::ProtoBuf.ProtoMember(3)]
        public RoleDataInfoDto roleDataInfoDto { get; set; }

    }

}

#pragma warning restore 1591, 0612, 3021
