// This file was generated by a tool; you should avoid making direct changes.
// Consider using 'partial classes' to extend these types
// Input: MapAreaInfo.proto

#pragma warning disable 1591, 0612, 3021
namespace com.server.game.protobuf.proto
{

    [global::ProtoBuf.ProtoContract()]
    public partial class MapAreaInfo : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        {
            return global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);
        }
        public MapAreaInfo()
        {
            newRoles = new global::System.Collections.Generic.List<PlayerMapLife>();
            newMonsters = new global::System.Collections.Generic.List<MonsterMapLife>();
            newNpcs = new global::System.Collections.Generic.List<NpcMapLife>();
            newMercenaries = new global::System.Collections.Generic.List<MercenaryMapLife>();
            newPets = new global::System.Collections.Generic.List<PetMapLife>();
            newPlayerImages = new global::System.Collections.Generic.List<PlayerMapLife>();
            mapLifeRoutes = new global::System.Collections.Generic.List<MapLifeRoute>();
            OnConstructor();
        }

        partial void OnConstructor();

        [global::ProtoBuf.ProtoMember(1)]
        public int mapId
        {
            get { return __pbn__mapId.GetValueOrDefault(); }
            set { __pbn__mapId = value; }
        }
        public bool ShouldSerializemapId()
        {
            return __pbn__mapId != null;
        }
        public void ResetmapId()
        {
            __pbn__mapId = null;
        }
        private int? __pbn__mapId;

        [global::ProtoBuf.ProtoMember(2)]
        public long currentTime
        {
            get { return __pbn__currentTime.GetValueOrDefault(); }
            set { __pbn__currentTime = value; }
        }
        public bool ShouldSerializecurrentTime()
        {
            return __pbn__currentTime != null;
        }
        public void ResetcurrentTime()
        {
            __pbn__currentTime = null;
        }
        private long? __pbn__currentTime;

        [global::ProtoBuf.ProtoMember(3)]
        public long[] removeLifes { get; set; }

        [global::ProtoBuf.ProtoMember(4)]
        public global::System.Collections.Generic.List<PlayerMapLife> newRoles { get; private set; }

        [global::ProtoBuf.ProtoMember(5)]
        public global::System.Collections.Generic.List<MonsterMapLife> newMonsters { get; private set; }

        [global::ProtoBuf.ProtoMember(6)]
        public global::System.Collections.Generic.List<NpcMapLife> newNpcs { get; private set; }

        [global::ProtoBuf.ProtoMember(7)]
        public global::System.Collections.Generic.List<MercenaryMapLife> newMercenaries { get; private set; }

        [global::ProtoBuf.ProtoMember(8)]
        public global::System.Collections.Generic.List<PetMapLife> newPets { get; private set; }

        [global::ProtoBuf.ProtoMember(9, Name = @"newPlayerImage")]
        public global::System.Collections.Generic.List<PlayerMapLife> newPlayerImages { get; private set; }

        [global::ProtoBuf.ProtoMember(10)]
        public global::System.Collections.Generic.List<MapLifeRoute> mapLifeRoutes { get; private set; }

    }

}

#pragma warning restore 1591, 0612, 3021
