// This file was generated by a tool; you should avoid making direct changes.
// Consider using 'partial classes' to extend these types
// Input: MapLife.proto

#pragma warning disable 1591, 0612, 3021
namespace com.server.game.protobuf.proto
{

    [global::ProtoBuf.ProtoContract()]
    public partial class MapLife : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        {
            return global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);
        }
        public MapLife()
        {
            Buffs = new global::System.Collections.Generic.List<BuffStruct>();
            shieldSyncInfos = new global::System.Collections.Generic.List<ShieldSyncInfo>();
            OnConstructor();
        }

        partial void OnConstructor();

        [global::ProtoBuf.ProtoMember(1, Name = @"id")]
        public long Id
        {
            get { return __pbn__Id.GetValueOrDefault(); }
            set { __pbn__Id = value; }
        }
        public bool ShouldSerializeId()
        {
            return __pbn__Id != null;
        }
        public void ResetId()
        {
            __pbn__Id = null;
        }
        private long? __pbn__Id;

        [global::ProtoBuf.ProtoMember(2, Name = @"px")]
        public float Px
        {
            get { return __pbn__Px.GetValueOrDefault(); }
            set { __pbn__Px = value; }
        }
        public bool ShouldSerializePx()
        {
            return __pbn__Px != null;
        }
        public void ResetPx()
        {
            __pbn__Px = null;
        }
        private float? __pbn__Px;

        [global::ProtoBuf.ProtoMember(3, Name = @"py")]
        public float Py
        {
            get { return __pbn__Py.GetValueOrDefault(); }
            set { __pbn__Py = value; }
        }
        public bool ShouldSerializePy()
        {
            return __pbn__Py != null;
        }
        public void ResetPy()
        {
            __pbn__Py = null;
        }
        private float? __pbn__Py;

        [global::ProtoBuf.ProtoMember(4, Name = @"hp")]
        public int Hp
        {
            get { return __pbn__Hp.GetValueOrDefault(); }
            set { __pbn__Hp = value; }
        }
        public bool ShouldSerializeHp()
        {
            return __pbn__Hp != null;
        }
        public void ResetHp()
        {
            __pbn__Hp = null;
        }
        private int? __pbn__Hp;

        [global::ProtoBuf.ProtoMember(5)]
        public int maxHp
        {
            get { return __pbn__maxHp.GetValueOrDefault(); }
            set { __pbn__maxHp = value; }
        }
        public bool ShouldSerializemaxHp()
        {
            return __pbn__maxHp != null;
        }
        public void ResetmaxHp()
        {
            __pbn__maxHp = null;
        }
        private int? __pbn__maxHp;

        [global::ProtoBuf.ProtoMember(6)]
        public int[] fightStates { get; set; }

        [global::ProtoBuf.ProtoMember(7, Name = @"buffs")]
        public global::System.Collections.Generic.List<BuffStruct> Buffs { get; private set; }

        [global::ProtoBuf.ProtoMember(8)]
        public global::System.Collections.Generic.List<ShieldSyncInfo> shieldSyncInfos { get; private set; }

        [global::ProtoBuf.ProtoMember(9)]
        public double moveSpeed
        {
            get { return __pbn__moveSpeed.GetValueOrDefault(); }
            set { __pbn__moveSpeed = value; }
        }
        public bool ShouldSerializemoveSpeed()
        {
            return __pbn__moveSpeed != null;
        }
        public void ResetmoveSpeed()
        {
            __pbn__moveSpeed = null;
        }
        private double? __pbn__moveSpeed;

        [global::ProtoBuf.ProtoMember(10)]
        [global::System.ComponentModel.DefaultValue("")]
        public string specialName
        {
            get { return __pbn__specialName ?? ""; }
            set { __pbn__specialName = value; }
        }
        public bool ShouldSerializespecialName()
        {
            return __pbn__specialName != null;
        }
        public void ResetspecialName()
        {
            __pbn__specialName = null;
        }
        private string __pbn__specialName;

        [global::ProtoBuf.ProtoMember(11)]
        public long campId
        {
            get { return __pbn__campId.GetValueOrDefault(); }
            set { __pbn__campId = value; }
        }
        public bool ShouldSerializecampId()
        {
            return __pbn__campId != null;
        }
        public void ResetcampId()
        {
            __pbn__campId = null;
        }
        private long? __pbn__campId;

    }

}

#pragma warning restore 1591, 0612, 3021
