// This file was generated by a tool; you should avoid making direct changes.
// Consider using 'partial classes' to extend these types
// Input: MapLifeRoute.proto

#pragma warning disable 1591, 0612, 3021
namespace com.server.game.protobuf.proto
{

    [global::ProtoBuf.ProtoContract()]
    public partial class MapLifeRoute : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        {
            return global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);
        }
        public MapLifeRoute()
        {
            Routes = new global::System.Collections.Generic.List<PrecisePosition>();
            OnConstructor();
        }

        partial void OnConstructor();

        [global::ProtoBuf.ProtoMember(1, Name = @"id")]
        public long Id
        {
            get { return __pbn__Id.GetValueOrDefault(); }
            set { __pbn__Id = value; }
        }
        public bool ShouldSerializeId()
        {
            return __pbn__Id != null;
        }
        public void ResetId()
        {
            __pbn__Id = null;
        }
        private long? __pbn__Id;

        [global::ProtoBuf.ProtoMember(2, Name = @"routes")]
        public global::System.Collections.Generic.List<PrecisePosition> Routes { get; private set; }

        [global::ProtoBuf.ProtoMember(3)]
        public long startTime
        {
            get { return __pbn__startTime.GetValueOrDefault(); }
            set { __pbn__startTime = value; }
        }
        public bool ShouldSerializestartTime()
        {
            return __pbn__startTime != null;
        }
        public void ResetstartTime()
        {
            __pbn__startTime = null;
        }
        private long? __pbn__startTime;

    }

}

#pragma warning restore 1591, 0612, 3021
