// This file was generated by a tool; you should avoid making direct changes.
// Consider using 'partial classes' to extend these types
// Input: MonsterMapLife.proto

#pragma warning disable 1591, 0612, 3021
namespace com.server.game.protobuf.proto
{

    [global::ProtoBuf.ProtoContract()]
    public partial class MonsterMapLife : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        {
            return global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);
        }
        public MonsterMapLife()
        {
            OnConstructor();
        }

        partial void OnConstructor();

        [global::ProtoBuf.ProtoMember(1)]
        public MapLife parentMonsterMapLife { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public long monsterId
        {
            get { return __pbn__monsterId.GetValueOrDefault(); }
            set { __pbn__monsterId = value; }
        }
        public bool ShouldSerializemonsterId()
        {
            return __pbn__monsterId != null;
        }
        public void ResetmonsterId()
        {
            __pbn__monsterId = null;
        }
        private long? __pbn__monsterId;

        [global::ProtoBuf.ProtoMember(3, Name = @"fixer")]
        public double Fixer
        {
            get { return __pbn__Fixer.GetValueOrDefault(); }
            set { __pbn__Fixer = value; }
        }
        public bool ShouldSerializeFixer()
        {
            return __pbn__Fixer != null;
        }
        public void ResetFixer()
        {
            __pbn__Fixer = null;
        }
        private double? __pbn__Fixer;

        [global::ProtoBuf.ProtoMember(6, Name = @"anims")]
        public MonsterAnim Anims { get; set; }

    }

}

#pragma warning restore 1591, 0612, 3021
