// This file was generated by a tool; you should avoid making direct changes.
// Consider using 'partial classes' to extend these types
// Input: NpcMapLife.proto

#pragma warning disable 1591, 0612, 3021
namespace com.server.game.protobuf.proto
{

    [global::ProtoBuf.ProtoContract()]
    public partial class NpcMapLife : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        {
            return global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);
        }
        public NpcMapLife()
        {
            OnConstructor();
        }

        partial void OnConstructor();

        [global::ProtoBuf.ProtoMember(1)]
        public MapLife parentNpcMapLife { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"id")]
        public long Id
        {
            get { return __pbn__Id.GetValueOrDefault(); }
            set { __pbn__Id = value; }
        }
        public bool ShouldSerializeId()
        {
            return __pbn__Id != null;
        }
        public void ResetId()
        {
            __pbn__Id = null;
        }
        private long? __pbn__Id;

        [global::ProtoBuf.ProtoMember(5)]
        public int npcBaseId
        {
            get { return __pbn__npcBaseId.GetValueOrDefault(); }
            set { __pbn__npcBaseId = value; }
        }
        public bool ShouldSerializenpcBaseId()
        {
            return __pbn__npcBaseId != null;
        }
        public void ResetnpcBaseId()
        {
            __pbn__npcBaseId = null;
        }
        private int? __pbn__npcBaseId;

    }

}

#pragma warning restore 1591, 0612, 3021
