// This file was generated by a tool; you should avoid making direct changes.
// Consider using 'partial classes' to extend these types
// Input: PetMapLife.proto

#pragma warning disable 1591, 0612, 3021
namespace com.server.game.protobuf.proto
{

    [global::ProtoBuf.ProtoContract()]
    public partial class PetMapLife : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        {
            return global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);
        }
        public PetMapLife()
        {
            OnConstructor();
        }

        partial void OnConstructor();

        [global::ProtoBuf.ProtoMember(1)]
        public MapLife parentPetMapLife { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public long petId
        {
            get { return __pbn__petId.GetValueOrDefault(); }
            set { __pbn__petId = value; }
        }
        public bool ShouldSerializepetId()
        {
            return __pbn__petId != null;
        }
        public void ResetpetId()
        {
            __pbn__petId = null;
        }
        private long? __pbn__petId;

        [global::ProtoBuf.ProtoMember(3)]
        public long roleId
        {
            get { return __pbn__roleId.GetValueOrDefault(); }
            set { __pbn__roleId = value; }
        }
        public bool ShouldSerializeroleId()
        {
            return __pbn__roleId != null;
        }
        public void ResetroleId()
        {
            __pbn__roleId = null;
        }
        private long? __pbn__roleId;

        [global::ProtoBuf.ProtoMember(4)]
        public int petCfgId
        {
            get { return __pbn__petCfgId.GetValueOrDefault(); }
            set { __pbn__petCfgId = value; }
        }
        public bool ShouldSerializepetCfgId()
        {
            return __pbn__petCfgId != null;
        }
        public void ResetpetCfgId()
        {
            __pbn__petCfgId = null;
        }
        private int? __pbn__petCfgId;

        [global::ProtoBuf.ProtoMember(5)]
        [global::System.ComponentModel.DefaultValue("")]
        public string petName
        {
            get { return __pbn__petName ?? ""; }
            set { __pbn__petName = value; }
        }
        public bool ShouldSerializepetName()
        {
            return __pbn__petName != null;
        }
        public void ResetpetName()
        {
            __pbn__petName = null;
        }
        private string __pbn__petName;

    }

}

#pragma warning restore 1591, 0612, 3021
