// This file was generated by a tool; you should avoid making direct changes.
// Consider using 'partial classes' to extend these types
// Input: PrecisePosition.proto

#pragma warning disable 1591, 0612, 3021
namespace com.server.game.protobuf.proto
{

    [global::ProtoBuf.ProtoContract()]
    public partial class PrecisePosition : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        {
            return global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);
        }
        public PrecisePosition()
        {
            OnConstructor();
        }

        partial void OnConstructor();

        [global::ProtoBuf.ProtoMember(1, Name = @"x")]
        public float X
        {
            get { return __pbn__X.GetValueOrDefault(); }
            set { __pbn__X = value; }
        }
        public bool ShouldSerializeX()
        {
            return __pbn__X != null;
        }
        public void ResetX()
        {
            __pbn__X = null;
        }
        private float? __pbn__X;

        [global::ProtoBuf.ProtoMember(2, Name = @"y")]
        public float Y
        {
            get { return __pbn__Y.GetValueOrDefault(); }
            set { __pbn__Y = value; }
        }
        public bool ShouldSerializeY()
        {
            return __pbn__Y != null;
        }
        public void ResetY()
        {
            __pbn__Y = null;
        }
        private float? __pbn__Y;

    }

}

#pragma warning restore 1591, 0612, 3021
