// This file was generated by a tool; you should avoid making direct changes.
// Consider using 'partial classes' to extend these types
// Input: RegisterRequestDto.proto

#pragma warning disable 1591, 0612, 3021
namespace com.server.game.protobuf.proto
{

    [global::ProtoBuf.ProtoContract()]
    public partial class RegisterRequestDto : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        {
            return global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);
        }
        public RegisterRequestDto()
        {
            OnConstructor();
        }

        partial void OnConstructor();

        [global::ProtoBuf.ProtoMember(1, Name = @"account")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Account
        {
            get { return __pbn__Account ?? ""; }
            set { __pbn__Account = value; }
        }
        public bool ShouldSerializeAccount()
        {
            return __pbn__Account != null;
        }
        public void ResetAccount()
        {
            __pbn__Account = null;
        }
        private string __pbn__Account;

        [global::ProtoBuf.ProtoMember(2, Name = @"name")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Name
        {
            get { return __pbn__Name ?? ""; }
            set { __pbn__Name = value; }
        }
        public bool ShouldSerializeName()
        {
            return __pbn__Name != null;
        }
        public void ResetName()
        {
            __pbn__Name = null;
        }
        private string __pbn__Name;

        [global::ProtoBuf.ProtoMember(3, Name = @"sex")]
        public int Sex
        {
            get { return __pbn__Sex.GetValueOrDefault(); }
            set { __pbn__Sex = value; }
        }
        public bool ShouldSerializeSex()
        {
            return __pbn__Sex != null;
        }
        public void ResetSex()
        {
            __pbn__Sex = null;
        }
        private int? __pbn__Sex;

        [global::ProtoBuf.ProtoMember(4, Name = @"vocation")]
        public int Vocation
        {
            get { return __pbn__Vocation.GetValueOrDefault(); }
            set { __pbn__Vocation = value; }
        }
        public bool ShouldSerializeVocation()
        {
            return __pbn__Vocation != null;
        }
        public void ResetVocation()
        {
            __pbn__Vocation = null;
        }
        private int? __pbn__Vocation;

        [global::ProtoBuf.ProtoMember(5, Name = @"platform")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Platform
        {
            get { return __pbn__Platform ?? ""; }
            set { __pbn__Platform = value; }
        }
        public bool ShouldSerializePlatform()
        {
            return __pbn__Platform != null;
        }
        public void ResetPlatform()
        {
            __pbn__Platform = null;
        }
        private string __pbn__Platform;

        [global::ProtoBuf.ProtoMember(6, Name = @"channel")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Channel
        {
            get { return __pbn__Channel ?? ""; }
            set { __pbn__Channel = value; }
        }
        public bool ShouldSerializeChannel()
        {
            return __pbn__Channel != null;
        }
        public void ResetChannel()
        {
            __pbn__Channel = null;
        }
        private string __pbn__Channel;

        [global::ProtoBuf.ProtoMember(7, Name = @"imei")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Imei
        {
            get { return __pbn__Imei ?? ""; }
            set { __pbn__Imei = value; }
        }
        public bool ShouldSerializeImei()
        {
            return __pbn__Imei != null;
        }
        public void ResetImei()
        {
            __pbn__Imei = null;
        }
        private string __pbn__Imei;

        [global::ProtoBuf.ProtoMember(9)]
        public int eyeColorId
        {
            get { return __pbn__eyeColorId.GetValueOrDefault(); }
            set { __pbn__eyeColorId = value; }
        }
        public bool ShouldSerializeeyeColorId()
        {
            return __pbn__eyeColorId != null;
        }
        public void ReseteyeColorId()
        {
            __pbn__eyeColorId = null;
        }
        private int? __pbn__eyeColorId;

        [global::ProtoBuf.ProtoMember(10)]
        public int hairColorId
        {
            get { return __pbn__hairColorId.GetValueOrDefault(); }
            set { __pbn__hairColorId = value; }
        }
        public bool ShouldSerializehairColorId()
        {
            return __pbn__hairColorId != null;
        }
        public void ResethairColorId()
        {
            __pbn__hairColorId = null;
        }
        private int? __pbn__hairColorId;

        [global::ProtoBuf.ProtoMember(11)]
        public int hairId
        {
            get { return __pbn__hairId.GetValueOrDefault(); }
            set { __pbn__hairId = value; }
        }
        public bool ShouldSerializehairId()
        {
            return __pbn__hairId != null;
        }
        public void ResethairId()
        {
            __pbn__hairId = null;
        }
        private int? __pbn__hairId;

        [global::ProtoBuf.ProtoMember(12)]
        public int eyeId
        {
            get { return __pbn__eyeId.GetValueOrDefault(); }
            set { __pbn__eyeId = value; }
        }
        public bool ShouldSerializeeyeId()
        {
            return __pbn__eyeId != null;
        }
        public void ReseteyeId()
        {
            __pbn__eyeId = null;
        }
        private int? __pbn__eyeId;

        [global::ProtoBuf.ProtoMember(13)]
        public int voiceId
        {
            get { return __pbn__voiceId.GetValueOrDefault(); }
            set { __pbn__voiceId = value; }
        }
        public bool ShouldSerializevoiceId()
        {
            return __pbn__voiceId != null;
        }
        public void ResetvoiceId()
        {
            __pbn__voiceId = null;
        }
        private int? __pbn__voiceId;

        [global::ProtoBuf.ProtoMember(14)]
        public int headIcon
        {
            get { return __pbn__headIcon.GetValueOrDefault(); }
            set { __pbn__headIcon = value; }
        }
        public bool ShouldSerializeheadIcon()
        {
            return __pbn__headIcon != null;
        }
        public void ResetheadIcon()
        {
            __pbn__headIcon = null;
        }
        private int? __pbn__headIcon;

    }

}

#pragma warning restore 1591, 0612, 3021
