// This file was generated by a tool; you should avoid making direct changes.
// Consider using 'partial classes' to extend these types
// Input: RoleDataInfoDto.proto

#pragma warning disable 1591, 0612, 3021
namespace com.server.game.protobuf.proto
{

    [global::ProtoBuf.ProtoContract()]
    public partial class RoleDataInfoDto : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        {
            return global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);
        }
        public RoleDataInfoDto()
        {
            OnConstructor();
        }

        partial void OnConstructor();

        [global::ProtoBuf.ProtoMember(1)]
        public int acrossServerId
        {
            get { return __pbn__acrossServerId.GetValueOrDefault(); }
            set { __pbn__acrossServerId = value; }
        }
        public bool ShouldSerializeacrossServerId()
        {
            return __pbn__acrossServerId != null;
        }
        public void ResetacrossServerId()
        {
            __pbn__acrossServerId = null;
        }
        private int? __pbn__acrossServerId;

        [global::ProtoBuf.ProtoMember(2)]
        public RoleInfoDto parentRoleDataInfoDto { get; set; }

    }

}

#pragma warning restore 1591, 0612, 3021
