// This file was generated by a tool; you should avoid making direct changes.
// Consider using 'partial classes' to extend these types
// Input: SCPlayerMapEnter.proto

#pragma warning disable 1591, 0612, 3021
namespace com.server.game.protobuf.proto
{

    [global::ProtoBuf.ProtoContract()]
    public partial class SCPlayerMapEnter : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        {
            return global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);
        }
        public SCPlayerMapEnter()
        {
            OnConstructor();
        }

        partial void OnConstructor();

        [global::ProtoBuf.ProtoMember(1)]
        public MapAreaInfo parentSCPlayerMapEnter { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public int mapLine
        {
            get { return __pbn__mapLine.GetValueOrDefault(); }
            set { __pbn__mapLine = value; }
        }
        public bool ShouldSerializemapLine()
        {
            return __pbn__mapLine != null;
        }
        public void ResetmapLine()
        {
            __pbn__mapLine = null;
        }
        private int? __pbn__mapLine;

    }

}

#pragma warning restore 1591, 0612, 3021
